[package]
name = "kzon-httpd"
version = "0.1.0"
authors = ["Anton Kobzev <kzon@ozon.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
urldecode = "0.1.1"
mio = "0.6.21"